name: Build Skyrim AE

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  PROJECT_NAME: XEMIUtil

permissions:
  actions: read
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Build
        run: xmake -y
      - name: Archive
        run: 7z a -tzip ${{ env.PROJECT_NAME }}.zip ./build/windows/x64/release/${{ env.PROJECT_NAME }}.dll ./build/windows/x64/release/${{ env.PROJECT_NAME }}.pdb
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Skyrim
          path: |
            ./build/windows/x64/release/LumaUtil.dll
            ./build/windows/x64/release/LumaUtil.pdb
      - name: Create & Upload Release
        id: upload-release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ env.PROJECT_NAME }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.PROJECT_NAME }} ${{ github.ref_name }}
        if: github.ref_type == 'tag'
